name: Pages
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Build and Commit
      #uses: sphinx-notes/pages@v2
      uses: umr-lops/xsar_slc@main
      with:
        requirements_path: ./docs/requirements_doc.txt
    - name: Push changes
      uses: ad-m/github-push-action@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages